#!/usr/bin/env bash

# Update the system and install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAProxy to distribute traffic to web-01 and web-02 using round-robin
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOL
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http-in
    bind *:80
    default_backend web-servers

backend web-servers
    balance roundrobin
    server 167789-web-01 54.237.103.34:80 check
    server 167789-web-02 54.88.248.174:80 check
EOL

# Ensure that HAProxy can be managed via an init script
sudo systemctl enable haproxy

# Restart HAProxy to apply the configuration
sudo systemctl restart haproxy

# Verify HAProxy status
sudo systemctl status haproxy
